import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import ImgCard from "../comps/ImgCard";
import Navbar from "../comps/Navbar/index";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href = "/boiler"> Go to boiler </Link>
      <Link href = "/about"> Go to about </Link>
    <Navbar> </Navbar>
      <ImgCard 
      bg = "#FDE8CA"
      tcl = "#abc980"
      />
      <ImgCard img = "http://placebear.com/300/300"/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">My first app! </a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <img src = "https://www.placebear.com/425/600"></img>
      </main>
    </div>
  )
}
